const actors = [
  {
    adult: false,
    gender: 2,
    id: 12799,
    known_for_department: "Acting",
    name: "Jeremy Piven",
    original_name: "Jeremy Piven",
    popularity: 257.457,
    profile_path: "/pqdR8zqAWF87chGYlbdYr0YfC7g.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/sd4xN5xi8tKRPrJOWwNiZEile7f.jpg",
        id: 920,
        title: "Cars",
        original_language: "en",
        original_title: "Cars",
        overview:
          "Lightning McQueen, a hotshot rookie race car driven to succeed, discovers that life is about the journey, not the finish line, when he finds himself unexpectedly detoured in the sleepy Route 66 town of Radiator Springs. On route across the country to the big Piston Cup Championship in California to compete against two seasoned pros, McQueen gets to know the town's offbeat characters.",
        poster_path: "/abW5AzHDaIK1n9C36VdAeOwORRA.jpg",
        media_type: "movie",
        genre_ids: [16, 12, 35, 10751],
        popularity: 69.939,
        release_date: "2006-06-08",
        video: false,
        vote_average: 6.9,
        vote_count: 13066,
      },
      {
        adult: false,
        backdrop_path: "/gU7EMTMV3d2ykb9630PAwLSvtSz.jpg",
        id: 9778,
        title: "Serendipity",
        original_language: "en",
        original_title: "Serendipity",
        overview:
          "Although strangers Sara and Jonathan are both already in relationships, they realize they have genuine chemistry after a chance encounter – but part company soon after. Years later, they each yearn to reunite, despite being destined for the altar. But to give true love a chance, they have to find one another again.",
        poster_path: "/srCE5lEIjVEG5eqWg9JcjZCK1aQ.jpg",
        media_type: "movie",
        genre_ids: [35, 10749, 18],
        popularity: 29.709,
        release_date: "2001-10-05",
        video: false,
        vote_average: 6.908,
        vote_count: 1772,
      },
      {
        adult: false,
        backdrop_path: "/6bNQuKFJIamipvYclG4MEbDSLM5.jpg",
        id: 93837,
        title: "So Undercover",
        original_language: "en",
        original_title: "So Undercover",
        overview:
          "When the FBI hires her to go undercover at a college sorority, Molly Morris (Miley Cyrus) must transform herself from a tough, streetwise private investigator to a refined, sophisticated university girl to help protect the daughter of a one-time Mobster. With several suspects on her list, Molly unexpectedly discovers that not everyone is who they appear to be, including herself.",
        poster_path: "/abR6e0FaWwwcEJEM4PY5VvjwBr1.jpg",
        media_type: "movie",
        genre_ids: [28, 35],
        popularity: 21.382,
        release_date: "2012-12-06",
        video: false,
        vote_average: 6.2,
        vote_count: 1081,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 106731,
    known_for_department: "Acting",
    name: "Nicolette Scorsese",
    original_name: "Nicolette Scorsese",
    popularity: 165.554,
    profile_path: "/i0PWIBj2dZQm76uepLhMO1188HS.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/1KYDPOC6ENDWCkW3TGCdca104hi.jpg",
        id: 5825,
        title: "National Lampoon's Christmas Vacation",
        original_language: "en",
        original_title: "National Lampoon's Christmas Vacation",
        overview:
          "It's Christmastime, and the Griswolds are preparing for a family seasonal celebration. But things never run smoothly for Clark, his wife Ellen, and their two kids. Clark's continual bad luck is worsened by his obnoxious family guests, but he manages to keep going, knowing that his Christmas bonus is due soon.",
        poster_path: "/gL8ZDtAy8vO95aAnv1H5CR4CGMA.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 147.93,
        release_date: "1989-11-30",
        video: false,
        vote_average: 7.224,
        vote_count: 2135,
      },
      {
        adult: false,
        backdrop_path: "/iiOfrrE9fwCrhmo8o5acrNJb5I7.jpg",
        id: 18215,
        title: "Boxing Helena",
        original_language: "en",
        original_title: "Boxing Helena",
        overview:
          "A top surgeon is besotted with a beautiful woman who once rebuffed him. Unable to come to terms with life without her, he tries to convince her that they need each other. She has other ideas, but a horrific accident leaves her at his mercy.",
        poster_path: "/fL8b32TY3Cxe661kztmzz5AlIM0.jpg",
        media_type: "movie",
        genre_ids: [18, 10749, 53, 27],
        popularity: 15.053,
        release_date: "1993-03-22",
        video: false,
        vote_average: 5.2,
        vote_count: 206,
      },
      {
        adult: false,
        backdrop_path: "/iARhC0Tor1XF0ADsCTvf0DEu3ZK.jpg",
        id: 41872,
        title: "Girls in Prison",
        original_language: "en",
        original_title: "Girls in Prison",
        overview:
          'Framed for the murder of a record company president in 1952 Hollywood, young, aspiring singer Aggie O\'Hanlon is sentenced to life in prison and tries to adjust to her life life behind bars in a hellish womens prison where she is befriended by other "lifer" inmates who help her out when Aggie finds herself marked for murder by an unknown source who thinks she knows more about the murder than she does.',
        poster_path: "/42gZLRZStmVH3shTSTj3iDZ9RBf.jpg",
        media_type: "movie",
        genre_ids: [80, 18, 53],
        popularity: 5.986,
        release_date: "1994-08-19",
        video: false,
        vote_average: 4.5,
        vote_count: 11,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 85034,
    known_for_department: "Acting",
    name: "Ranbir Kapoor",
    original_name: "Ranbir Kapoor",
    popularity: 158.901,
    profile_path: "/ymYNHV9luwgyrw17NXHqbOWTQkg.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/lnNEmbGoxcSoO69NeavliNUxT3O.jpg",
        id: 127501,
        title: "Barfi!",
        original_language: "hi",
        original_title: "बर्फी!",
        overview:
          "Three young people learn that love can neither be defined nor contained by society's definition of normal and abnormal.",
        poster_path: "/8lVuWmArvr41CvyvpgI3elD5iB1.jpg",
        media_type: "movie",
        genre_ids: [18, 10749, 35],
        popularity: 18.963,
        release_date: "2012-09-13",
        video: false,
        vote_average: 7.5,
        vote_count: 293,
      },
      {
        adult: false,
        backdrop_path: "/Wi9bgiwfJPYKFcJIiUqCNDFNtf.jpg",
        id: 185008,
        title: "Yeh Jawaani Hai Deewani",
        original_language: "hi",
        original_title: "ये जवानी है दीवानी",
        overview:
          "Bunny and Naina meet when they graduate from college and again in their late 20s.",
        poster_path: "/em39H81XLCDgXsI7V4IcBZseEO6.jpg",
        media_type: "movie",
        genre_ids: [10749, 35],
        popularity: 18.775,
        release_date: "2013-05-31",
        video: false,
        vote_average: 7.3,
        vote_count: 237,
      },
      {
        adult: false,
        backdrop_path: "/YmrlTsqhmFsWo50QawaKTHOql7.jpg",
        id: 393445,
        title: "Ae Dil Hai Mushkil",
        original_language: "hi",
        original_title: "ऐ दिल है मुश्किल",
        overview:
          "Ayan falls in love with his soulmate, Alizeh, but she doesn’t reciprocate the feeling. Later, a relationship with Saba helps him realize Alizeh’s value in his life, irrespective of their relationship status.",
        poster_path: "/1BDnQBOIUsPFnlLw35gManvHKUs.jpg",
        media_type: "movie",
        genre_ids: [10749, 18],
        popularity: 12.129,
        release_date: "2016-10-27",
        video: false,
        vote_average: 6.4,
        vote_count: 182,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 974169,
    known_for_department: "Acting",
    name: "Jenna Ortega",
    original_name: "Jenna Ortega",
    popularity: 152.407,
    profile_path: "/q1NRzyZQlYkxLY07GO9NVPkQnu8.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        id: 119051,
        name: "Wednesday",
        original_language: "en",
        original_name: "Wednesday",
        overview:
          "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
        poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        media_type: "tv",
        genre_ids: [10765, 9648, 35],
        popularity: 419.668,
        first_air_date: "2022-11-23",
        vote_average: 8.523,
        vote_count: 7755,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/ifUfE79O1raUwbaQRIB7XnFz5ZC.jpg",
        id: 646385,
        title: "Scream",
        original_language: "en",
        original_title: "Scream",
        overview:
          "Twenty-five years after a streak of brutal murders shocked the quiet town of Woodsboro, a new killer has donned the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town’s deadly past.",
        poster_path: "/971Kqs1q4nuSc9arn1QAuKYbfxy.jpg",
        media_type: "movie",
        genre_ids: [27, 9648, 53],
        popularity: 75.945,
        release_date: "2022-01-12",
        video: false,
        vote_average: 6.697,
        vote_count: 2894,
      },
      {
        adult: false,
        backdrop_path: "/70Rm9ItxKuEKN8iu6rNjfwAYUCJ.jpg",
        id: 760104,
        title: "X",
        original_language: "en",
        original_title: "X",
        overview:
          "In 1979, a group of young filmmakers set out to make an adult film in rural Texas, but when their reclusive, elderly hosts catch them in the act, the cast find themselves fighting for their lives.",
        poster_path: "/woTQx9Q4b8aO13jR9dsj8C9JESy.jpg",
        media_type: "movie",
        genre_ids: [27, 53, 9648],
        popularity: 121.459,
        release_date: "2022-03-17",
        video: false,
        vote_average: 6.751,
        vote_count: 2440,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 1232179,
    known_for_department: "Acting",
    name: "Anna Slotky",
    original_name: "Anna Slotky",
    popularity: 137.302,
    profile_path: "/6NvXc8Z8t8rccjliVPparVeUGj0.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/pnkcE3Q3fPNM9XzWEN1gJJRYYX4.jpg",
        id: 772,
        title: "Home Alone 2: Lost in New York",
        original_language: "en",
        original_title: "Home Alone 2: Lost in New York",
        overview:
          "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas Eve.",
        poster_path: "/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg",
        media_type: "movie",
        genre_ids: [35, 10751, 12],
        popularity: 309.709,
        release_date: "1992-11-19",
        video: false,
        vote_average: 6.7,
        vote_count: 8828,
      },
      {
        adult: false,
        backdrop_path: "/bCFhGBYSLFSVdZmBZ6sENhMmi2Z.jpg",
        id: 771,
        title: "Home Alone",
        original_language: "en",
        original_title: "Home Alone",
        overview:
          "Eight-year-old Kevin McCallister makes the most of the situation after his family unwittingly leaves him behind when they go on Christmas vacation. But when a pair of bungling burglars set their sights on Kevin's house, the plucky kid stands ready to defend his territory. By planting booby traps galore, adorably mischievous Kevin stands his ground as his frantic mother attempts to race home before Christmas Day.",
        poster_path: "/9wSbe4CwObACCQvaUVhWQyLR5Vz.jpg",
        media_type: "movie",
        genre_ids: [35, 10751],
        popularity: 16.338,
        release_date: "1990-11-16",
        video: false,
        vote_average: 7.416,
        vote_count: 10326,
      },
      {
        adult: false,
        backdrop_path: "/eZmgVaSzSYBCw1pIX1yNetEjzc0.jpg",
        id: 155,
        name: "3rd Rock from the Sun",
        original_language: "en",
        original_name: "3rd Rock from the Sun",
        overview:
          "3rd Rock from the Sun is an American sitcom that aired from 1996 to 2001 on NBC. The show is about four extraterrestrials who are on an expedition to Earth, which they consider to be a very insignificant planet. The extraterrestrials pose as a human family in order to observe the behavior of human beings.",
        poster_path: "/sUB4lZghNnwQywKqgjIfJsyBqI2.jpg",
        media_type: "tv",
        genre_ids: [10751, 10765, 35, 18],
        popularity: 758.482,
        first_air_date: "1996-01-09",
        vote_average: 7.498,
        vote_count: 429,
        origin_country: ["US"],
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 976,
    known_for_department: "Acting",
    name: "Jason Statham",
    original_name: "Jason Statham",
    popularity: 137.281,
    profile_path: "/whNwkEQYWLFJA8ij0WyOOAD5xhQ.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/ysKahAEPP8h6MInuLjr0xuZOTjh.jpg",
        id: 107,
        title: "Snatch",
        original_language: "en",
        original_title: "Snatch",
        overview:
          "Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.",
        poster_path: "/56mOJth6DJ6JhgoE2jtpilVqJO.jpg",
        media_type: "movie",
        genre_ids: [80, 35],
        popularity: 44.071,
        release_date: "2000-09-01",
        video: false,
        vote_average: 7.805,
        vote_count: 8436,
      },
      {
        adult: false,
        backdrop_path: "/iP1cjN3ZGs1yJXROKaUj9hi1yF2.jpg",
        id: 345940,
        title: "The Meg",
        original_language: "en",
        original_title: "The Meg",
        overview:
          "A deep sea submersible pilot revisits his past fears in the Mariana Trench, and accidentally unleashes the seventy foot ancestor of the Great White Shark believed to be extinct.",
        poster_path: "/eyWICPcxOuTcDDDbTMOZawoOn8d.jpg",
        media_type: "movie",
        genre_ids: [28, 878, 27],
        popularity: 95.384,
        release_date: "2018-08-09",
        video: false,
        vote_average: 6.255,
        vote_count: 7165,
      },
      {
        adult: false,
        backdrop_path: "/kWt1OcPgwO1ssu57wgTKmq38JYw.jpg",
        id: 4108,
        title: "The Transporter",
        original_language: "en",
        original_title: "The Transporter",
        overview:
          "Former Special Forces officer, Frank Martin will deliver anything to anyone for the right price, and his no-questions-asked policy puts him in high demand. But when he realizes his latest cargo is alive, it sets in motion a dangerous chain of events. The bound and gagged Lai is being smuggled to France by a shady American businessman, and Frank works to save her as his own illegal activities are uncovered by a French detective.",
        poster_path: "/v3QIFUWgtVN4wejVuDZowuyJ20W.jpg",
        media_type: "movie",
        genre_ids: [28, 80, 53],
        popularity: 45.034,
        release_date: "2002-10-02",
        video: false,
        vote_average: 6.698,
        vote_count: 4978,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 2502703,
    known_for_department: "Acting",
    name: "Alyson Gorske",
    original_name: "Alyson Gorske",
    popularity: 133.251,
    profile_path: "/aqohlkcnI9yZdRmgDWjipCncmh8.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/9fWW38bLEdofv77bUPLIu8zLN6.jpg",
        id: 844636,
        title: "Jungle Run",
        original_language: "en",
        original_title: "Jungle Run",
        overview:
          "A brother and sister's journey into the jungle to find their missing father.",
        poster_path: "/7qz8G0DcgLUkJSbLU5YpzQYlOnb.jpg",
        media_type: "movie",
        genre_ids: [12, 28],
        popularity: 13.817,
        release_date: "2021-06-24",
        video: false,
        vote_average: 6.1,
        vote_count: 99,
      },
      {
        adult: false,
        backdrop_path: "/c8XIFuJCPTtTJdSRpqnUoMr6eK1.jpg",
        id: 667574,
        title: "Battle Star Wars",
        original_language: "en",
        original_title: "Battle Star Wars",
        overview:
          "When the leader of the evil Coalition threatens to destroy a Rebel planet for its resources, his daughter will have no choice but to join the Rebel side and fight for what is right.",
        poster_path: "/ocA0ECiFoB4d1HITyEDQlLk7x84.jpg",
        media_type: "movie",
        genre_ids: [878, 28],
        popularity: 9.456,
        release_date: "2020-01-28",
        video: false,
        vote_average: 5.1,
        vote_count: 36,
      },
      {
        adult: false,
        backdrop_path: "/aDQBgiWx2hLwKXbPrc92ILoO5LP.jpg",
        id: 1081353,
        title: "Amy's F**k It List",
        original_language: "en",
        original_title: "Amy's F**k It List",
        overview:
          "Plain and basic Amy receives news that suddenly turns her world upside down. Together with her outspoken and bold Sister Mary, the pair embark on a mission to set things right in the world and reconnect their once lost bond along the way.",
        poster_path: "/m4lFMnotILTWriXPoEhTIuVRNPr.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 4.238,
        release_date: "2023-02-04",
        video: false,
        vote_average: 5,
        vote_count: 5,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 1878952,
    known_for_department: "Acting",
    name: "Song Kang",
    original_name: "Song Kang",
    popularity: 132.063,
    profile_path: "/dMUXkMfkTEw3qrJisk0mQCQxmBI.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/mceCXNTny6a5F3rQgShLoyARw4l.jpg",
        id: 96648,
        name: "Sweet Home",
        original_language: "ko",
        original_name: "스위트홈",
        overview:
          "As humans turn into savage monsters and the world plunges into terror, a handful of survivors fight for their lives — and to hold on to their humanity.",
        poster_path: "/7K8XmVrvwYbnQSg7lI9VOmf7suO.jpg",
        media_type: "tv",
        genre_ids: [18, 10765, 80],
        popularity: 887.261,
        first_air_date: "2020-12-18",
        vote_average: 8.395,
        vote_count: 1142,
        origin_country: ["KR"],
      },
      {
        adult: false,
        backdrop_path: "/mXouvrZbn8YpZMURGvw30QK8qfo.jpg",
        id: 89641,
        name: "Love Alarm",
        original_language: "ko",
        original_name: "좋아하면 울리는",
        overview:
          "Love Alarm is an app that tells you if someone within a 10-meter radius has a crush on you. It quickly becomes a social phenomenon. While everyone talks about it and uses it to test their love and popularity, Jojo is one of the few people who have yet to download the app. However, she soon faces a love triangle situation between Sun-oh whom she starts to have feelings for, and Hye-young, who has had a huge crush on her.",
        poster_path: "/s87JyAWtRLLlmsYWXTED1l8henB.jpg",
        media_type: "tv",
        genre_ids: [18, 10765],
        popularity: 50.695,
        first_air_date: "2019-08-22",
        vote_average: 8.404,
        vote_count: 1859,
        origin_country: ["KR"],
      },
      {
        adult: false,
        backdrop_path: "/iSAH9nH10hke3IW9woUSnTmSHm4.jpg",
        id: 119464,
        name: "Navillera",
        original_language: "ko",
        original_name: "나빌레라",
        overview:
          "A 70-year-old with a dream and a 23-year-old with a gift lift each other out of harsh realities and rise to the challenge of becoming ballerinos.",
        poster_path: "/pBd6pEhszsWk95TrUqo4bdXhH8T.jpg",
        media_type: "tv",
        genre_ids: [18],
        popularity: 24.592,
        first_air_date: "2021-03-22",
        vote_average: 8.6,
        vote_count: 168,
        origin_country: ["KR"],
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 27972,
    known_for_department: "Acting",
    name: "Josh Hutcherson",
    original_name: "Josh Hutcherson",
    popularity: 128.837,
    profile_path: "/npowygg8rH7uJ4v7rAoDMsHBhNq.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/yDbyVT8tTOgXUrUXNkHEUqbxb1K.jpg",
        id: 70160,
        title: "The Hunger Games",
        original_language: "en",
        original_title: "The Hunger Games",
        overview:
          "Every year in the ruins of what was once North America, the nation of Panem forces each of its twelve districts to send a teenage boy and girl to compete in the Hunger Games.  Part twisted entertainment, part government intimidation tactic, the Hunger Games are a nationally televised event in which “Tributes” must fight with one another until one survivor remains.  Pitted against highly-trained Tributes who have prepared for these Games their entire lives, Katniss is forced to rely upon her sharp instincts as well as the mentorship of drunken former victor Haymitch Abernathy.  If she’s ever to return home to District 12, Katniss must make impossible choices in the arena that weigh survival against humanity and life against love. The world will be watching.",
        poster_path: "/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
        media_type: "movie",
        genre_ids: [878, 12, 14],
        popularity: 97.796,
        release_date: "2012-03-12",
        video: false,
        vote_average: 7.2,
        vote_count: 20920,
      },
      {
        adult: false,
        backdrop_path: "/dIi0De3LzEVSQHEUlh0Q2zUpmeW.jpg",
        id: 101299,
        title: "The Hunger Games: Catching Fire",
        original_language: "en",
        original_title: "The Hunger Games: Catching Fire",
        overview:
          'Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a "Victor\'s Tour" of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.',
        poster_path: "/vrQHDXjVmbYzadOXQ0UaObunoy2.jpg",
        media_type: "movie",
        genre_ids: [12, 28, 878],
        popularity: 139.113,
        release_date: "2013-11-15",
        video: false,
        vote_average: 7.425,
        vote_count: 16424,
      },
      {
        adult: false,
        backdrop_path: "/tFlSDoWQsAZ2qjICKzfP5Yw6zM5.jpg",
        id: 131631,
        title: "The Hunger Games: Mockingjay - Part 1",
        original_language: "en",
        original_title: "The Hunger Games: Mockingjay - Part 1",
        overview:
          "Katniss Everdeen reluctantly becomes the symbol of a mass rebellion against the autocratic Capitol.",
        poster_path: "/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
        media_type: "movie",
        genre_ids: [878, 12, 53],
        popularity: 313.684,
        release_date: "2014-11-19",
        video: false,
        vote_average: 6.803,
        vote_count: 14956,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 2359226,
    known_for_department: "Acting",
    name: "Aya Asahina",
    original_name: "Aya Asahina",
    popularity: 122.745,
    profile_path: "/zF3la0KvayUV3uACYPiBgCRIQcI.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/bKxiLRPVWe2nZXCzt6JPr5HNWYm.jpg",
        id: 110316,
        name: "Alice in Borderland",
        original_language: "ja",
        original_name: "今際の国のアリス",
        overview:
          "With his two friends, a video-game-obsessed young man finds himself in a strange version of Tokyo where they must compete in dangerous games to win.",
        poster_path: "/20mOwAAPwZ1vLQkw0fvuQHiG7bO.jpg",
        media_type: "tv",
        genre_ids: [18, 9648, 10759],
        popularity: 386.78,
        first_air_date: "2020-12-10",
        vote_average: 8.185,
        vote_count: 1716,
        origin_country: ["JP"],
      },
      {
        adult: false,
        backdrop_path: null,
        id: 677602,
        title: "Grand Blue",
        original_language: "ja",
        original_title: "ぐらんぶる",
        overview:
          "Iori’s only dream is to go to college on a remote island—but when he gets roped into the school’s debaucherous, alcohol-indulgent diving club his hope for a sparkling campus life is thrown into chaos.",
        poster_path: "/iZGnDnstcdorT0zJRpWzSQlMNz6.jpg",
        media_type: "movie",
        genre_ids: [35],
        popularity: 9.414,
        release_date: "2020-08-07",
        video: false,
        vote_average: 6,
        vote_count: 12,
      },
      {
        adult: false,
        backdrop_path: "/iNpbnWI2vQWGdPC9Pbt1RnV71R5.jpg",
        id: 91414,
        name: "Runway 24",
        original_language: "ja",
        original_name: "ランウェイ 24",
        overview:
          "Inoue Momoko admires her late father, who was a pilot. She begins work as a co-pilot at a low-cost airline. Under Captain Shinkai Kohei’s instructions, who knew her father, Inoue Momoko works hard to become a captain and her boyfriend Umino Daisuke supports her dream too.\n\nOne day, Inoue Momoko has a problem with a passenger complaining about the limit for carry-on baggage. At that time, Katsuki Tetsuya looks at the situation.",
        poster_path: "/2j2p3MF2GpSMHAFaYTgIRQeVOHa.jpg",
        media_type: "tv",
        genre_ids: [10751, 18],
        popularity: 11.122,
        first_air_date: "2019-07-06",
        vote_average: 6.7,
        vote_count: 3,
        origin_country: ["JP"],
      },
    ],
  },
  {
    adult: false,
    gender: 0,
    id: 3234630,
    known_for_department: "Acting",
    name: "Sangeeth Shobhan",
    original_name: "Sangeeth Shobhan",
    popularity: 111.314,
    profile_path: "/7Vox31bH7XmgPNJzMKGa4uGyjW8.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/jBnnkkXRZ0pV3Tw31Z2ALO638wA.jpg",
        id: 1187075,
        title: "MAD",
        original_language: "te",
        original_title: "MAD",
        overview:
          "Set in an engineering college and revolves around the antics of the students there, primarily the boys, who get a kick out of torturing the hostel warden.",
        poster_path: "/nDpOmgBfQZwOpFBcgokQGqd74r1.jpg",
        media_type: "movie",
        genre_ids: [35, 10749, 18],
        popularity: 5.648,
        release_date: "2023-10-06",
        video: false,
        vote_average: 7,
        vote_count: 4,
      },
      {
        adult: false,
        backdrop_path: "/1jof3bGVg67HLmvRHfTzqb2IODO.jpg",
        id: 138179,
        name: "Oka Chinna Family Story",
        original_language: "te",
        original_name: "ఒక చిన్న Family Story",
        overview:
          "Mahesh and his mother embark on an adventurous journey filled with hilarious situations as they try to make quick money to repay a huge loan.",
        poster_path: "/u1Tq2Qqb1oUJ6WSzVJqWk03LzEl.jpg",
        media_type: "tv",
        genre_ids: [35, 10751],
        popularity: 6.921,
        first_air_date: "2021-11-19",
        vote_average: 7.5,
        vote_count: 2,
        origin_country: ["IN"],
      },
      {
        adult: false,
        backdrop_path: "/d7jfcyPb5ZncLyhPFNjpuIeeZ1y.jpg",
        id: 1119091,
        title: "Prema Vimanam",
        original_language: "te",
        original_title: "ప్రేమ విమానం",
        overview:
          "Two kids with a dream to board a flight cross paths with a young couple who must urgently catch the flight to start a new life.",
        poster_path: "/9eljOANAd6HafUDdmp3xnmkpnt8.jpg",
        media_type: "movie",
        genre_ids: [18, 35],
        popularity: 2.564,
        release_date: "2023-10-13",
        video: false,
        vote_average: 7,
        vote_count: 1,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 6161,
    known_for_department: "Acting",
    name: "Jennifer Connelly",
    original_name: "Jennifer Connelly",
    popularity: 106.581,
    profile_path: "/3oYDftEbM3YgBiHYcbbIPRNZrTL.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/zbpZOYrRCxEF8lFT5JC8XodEggC.jpg",
        id: 453,
        title: "A Beautiful Mind",
        original_language: "en",
        original_title: "A Beautiful Mind",
        overview:
          "John Nash is a brilliant but asocial mathematician fighting schizophrenia. After he accepts secret work in cryptography, his life takes a turn for the nightmarish.",
        poster_path: "/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
        media_type: "movie",
        genre_ids: [18, 10749],
        popularity: 105.533,
        release_date: "2001-12-14",
        video: false,
        vote_average: 7.855,
        vote_count: 9593,
      },
      {
        adult: false,
        backdrop_path: "/s5R6kTMfOxkGit96A8lqcDL4uVk.jpg",
        id: 641,
        title: "Requiem for a Dream",
        original_language: "en",
        original_title: "Requiem for a Dream",
        overview:
          "The hopes and dreams of four ambitious people are shattered when their drug addictions begin spiraling out of control. A look into addiction and how it overcomes the mind and body.",
        poster_path: "/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg",
        media_type: "movie",
        genre_ids: [80, 18],
        popularity: 19.561,
        release_date: "2000-10-06",
        video: false,
        vote_average: 8.025,
        vote_count: 9300,
      },
      {
        adult: false,
        backdrop_path: "/5z75Q6nqgwgYfpMB9fVHQcw9gMz.jpg",
        id: 86834,
        title: "Noah",
        original_language: "en",
        original_title: "Noah",
        overview:
          "A man who suffers visions of an apocalyptic deluge takes measures to protect his family from the coming flood.",
        poster_path: "/trtD17IqSWV9Nbn4OILztc9GuCX.jpg",
        media_type: "movie",
        genre_ids: [18, 12],
        popularity: 33.98,
        release_date: "2014-03-07",
        video: false,
        vote_average: 5.658,
        vote_count: 5901,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 224513,
    known_for_department: "Acting",
    name: "Ana de Armas",
    original_name: "Ana de Armas",
    popularity: 106.309,
    profile_path: "/3vxvsmYLTf4jnr163SUlBIw51ee.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/ilRyazdMJwN05exqhwK4tMKBYZs.jpg",
        id: 335984,
        title: "Blade Runner 2049",
        original_language: "en",
        original_title: "Blade Runner 2049",
        overview:
          "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos. K's discovery leads him on a quest to find Rick Deckard, a former LAPD blade runner who has been missing for 30 years.",
        poster_path: "/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
        media_type: "movie",
        genre_ids: [878, 18],
        popularity: 137.747,
        release_date: "2017-10-04",
        video: false,
        vote_average: 7.55,
        vote_count: 12573,
      },
      {
        adult: false,
        backdrop_path: "/4HWAQu28e2yaWrtupFPGFkdNU7V.jpg",
        id: 546554,
        title: "Knives Out",
        original_language: "en",
        original_title: "Knives Out",
        overview:
          "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan's untimely death.",
        poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
        media_type: "movie",
        genre_ids: [35, 80, 9648],
        popularity: 54.403,
        release_date: "2019-11-27",
        video: false,
        vote_average: 7.845,
        vote_count: 11352,
      },
      {
        adult: false,
        backdrop_path: "/3Mnbw4gOYz5BNZB9PhZ2cyBSQum.jpg",
        id: 308266,
        title: "War Dogs",
        original_language: "en",
        original_title: "War Dogs",
        overview:
          "Based on the true story of two young men, David Packouz and Efraim Diveroli, who won a $300 million contract from the Pentagon to arm America's allies in Afghanistan.",
        poster_path: "/uH9qGH5XS1iZXCSb3tgu40dxQoh.jpg",
        media_type: "movie",
        genre_ids: [35, 80, 18],
        popularity: 31.847,
        release_date: "2016-08-18",
        video: false,
        vote_average: 6.908,
        vote_count: 4569,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 4068148,
    known_for_department: "Acting",
    name: "Madeleine Yuna Voyles",
    original_name: "Madeleine Yuna Voyles",
    popularity: 104.765,
    profile_path: "/mLKvNuCJSgyK0WdLd4ogO81sOO1.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/kjQBrc00fB2RjHZB3PGR4w9ibpz.jpg",
        id: 670292,
        title: "The Creator",
        original_language: "en",
        original_title: "The Creator",
        overview:
          "Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.",
        poster_path: "/vBZ0qvaRxqEhZwl6LWmruJqWE8Z.jpg",
        media_type: "movie",
        genre_ids: [28, 12, 18],
        popularity: 738.648,
        release_date: "2023-09-27",
        video: false,
        vote_average: 7.129,
        vote_count: 1363,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 1190668,
    known_for_department: "Acting",
    name: "Timothée Chalamet",
    original_name: "Timothée Chalamet",
    popularity: 103.861,
    profile_path: "/BE2sdjpgsa2rNTFa66f7upkaOP.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/zvOJawrnmgK0sL293mOXOdLvTXQ.jpg",
        id: 398818,
        title: "Call Me by Your Name",
        original_language: "en",
        original_title: "Call Me by Your Name",
        overview:
          "In 1980s Italy, a relationship begins between seventeen-year-old teenage Elio and the older adult man hired as his father's research assistant.",
        poster_path: "/mZ4gBdfkhP9tvLH1DO4m4HYtiyi.jpg",
        media_type: "movie",
        genre_ids: [10749, 18],
        popularity: 47.093,
        release_date: "2017-09-01",
        video: false,
        vote_average: 8.164,
        vote_count: 11461,
      },
      {
        adult: false,
        backdrop_path: "/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg",
        id: 438631,
        title: "Dune",
        original_language: "en",
        original_title: "Dune",
        overview:
          "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet's exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity's greatest potential-only those who can conquer their fear will survive.",
        poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
        media_type: "movie",
        genre_ids: [878, 12],
        popularity: 96.327,
        release_date: "2021-09-15",
        video: false,
        vote_average: 7.786,
        vote_count: 9664,
      },
      {
        adult: false,
        backdrop_path: "/urwWVsciRiNSmhtMJcck0noWAXr.jpg",
        id: 504949,
        title: "The King",
        original_language: "en",
        original_title: "The King",
        overview:
          "England, 15th century. Hal, a capricious prince who lives among the populace far from court, is forced by circumstances to reluctantly accept the throne and become Henry V.",
        poster_path: "/8u0QBGUbZcBW59VEAdmeFl9g98N.jpg",
        media_type: "movie",
        genre_ids: [18, 36, 10752],
        popularity: 29.354,
        release_date: "2019-10-11",
        video: false,
        vote_average: 7.153,
        vote_count: 2963,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 2604515,
    known_for_department: "Acting",
    name: "Emma Myers",
    original_name: "Emma Myers",
    popularity: 102.335,
    profile_path: "/e5eTDKstLsUKKfmwgiJsDakcvly.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
        id: 119051,
        name: "Wednesday",
        original_language: "en",
        original_name: "Wednesday",
        overview:
          "Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
        poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
        media_type: "tv",
        genre_ids: [10765, 9648, 35],
        popularity: 419.668,
        first_air_date: "2022-11-23",
        vote_average: 8.523,
        vote_count: 7755,
        origin_country: ["US"],
      },
      {
        adult: false,
        backdrop_path: "/fvUmnxS9xaUUl0eWygvcA1hPdTV.jpg",
        id: 801335,
        title: "Girl in the Basement",
        original_language: "en",
        original_title: "Girl in the Basement",
        overview:
          "Sara is a teen girl who is looking forward to her 18th birthday to move away from her controlling father Don. But before she could even blow out the candles, Don imprisons her in the basement of their home.",
        poster_path: "/qmddUxRwbsxHa7oEXm4PWh1KZe8.jpg",
        media_type: "movie",
        genre_ids: [80, 53, 10770],
        popularity: 48.529,
        release_date: "2021-02-27",
        video: false,
        vote_average: 7.713,
        vote_count: 595,
      },
      {
        adult: false,
        backdrop_path: "/8WBh82iOYRykS3C05RipWTX70xh.jpg",
        id: 798021,
        title: "Family Switch",
        original_language: "en",
        original_title: "Family Switch",
        overview:
          "When the Walker family members switch bodies with each other during a rare planetary alignment, their hilarious journey to find their way back to normal will bring them closer together than they ever thought possible.",
        poster_path: "/g8Gwitm4CtZBSYhLeSY4Z3Xwwcg.jpg",
        media_type: "movie",
        genre_ids: [35, 14, 10751],
        popularity: 303.069,
        release_date: "2023-11-30",
        video: false,
        vote_average: 6.399,
        vote_count: 217,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 2100209,
    known_for_department: "Acting",
    name: "Tripti Dimri",
    original_name: "Tripti Dimri",
    popularity: 102.082,
    profile_path: "/fiyFyDfJ6t8hSgK49B1g18J13KE.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/hwBFGNabkGv2ZIyFUnCTSSmprf7.jpg",
        id: 714338,
        title: "Bulbbul",
        original_language: "hi",
        original_title: "बुलबुल",
        overview:
          "A child bride grows up to be an enigmatic woman presiding over her household, harboring a painful past as supernatural murders of men plague her village.",
        poster_path: "/4XYEqHqvcf6vxFhNyeKZz5xbUfV.jpg",
        media_type: "movie",
        genre_ids: [27, 14],
        popularity: 15.623,
        release_date: "2020-06-24",
        video: false,
        vote_average: 6.668,
        vote_count: 113,
      },
      {
        adult: false,
        backdrop_path: "/iwRZjIftnFy2vjSAQEKU3JUgv3m.jpg",
        id: 934419,
        title: "Qala",
        original_language: "hi",
        original_title: "क़ला",
        overview:
          "Haunted by her past, a talented singer with a rising career copes with the pressure of success, a mother's disdain and the voices of doubt within her.",
        poster_path: "/4d2xoBGXMpfeQ6QgpVI4qm34bKP.jpg",
        media_type: "movie",
        genre_ids: [18, 10402],
        popularity: 10.21,
        release_date: "2022-11-24",
        video: false,
        vote_average: 6.5,
        vote_count: 20,
      },
      {
        adult: false,
        backdrop_path: "/cCV4rIBtBjSDmAbP1SFaRz7CZV4.jpg",
        id: 404604,
        title: "Mom",
        original_language: "hi",
        original_title: "माँ",
        overview:
          "After her stepdaughter is sexually assaulted at a party, a furious mother sets out to destroy the lives of the four perpetrators who walked free.",
        poster_path: "/zZwbntqdfKdVgzH1RoMHa99g0mJ.jpg",
        media_type: "movie",
        genre_ids: [80, 18, 53],
        popularity: 10.196,
        release_date: "2017-07-07",
        video: false,
        vote_average: 7.6,
        vote_count: 186,
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 1914924,
    known_for_department: "Acting",
    name: "Miles Wei",
    original_name: "Miles Wei",
    popularity: 92.606,
    profile_path: "/fT4v4LTDXGEFGHe7ZAaRTtqBFYM.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/q0dz7lf8y44KhBBnxyq8B5bKJxf.jpg",
        id: 128926,
        name: "Unforgettable Love",
        original_language: "zh",
        original_name: "贺先生的恋恋不忘",
        overview:
          'The drama revolves around He Qiao Yan, CEO of Heshi Group, and Qin Yi Yue, a child psychologist. It tells the story of a rational and indifferent man and a soft, optimistic, considerate, and meticulous psychologist, whose relationship develops from acquaintance to love. Adapted from the web novel "Mr He\'s Love is Not Forgotten" by Qin Ye.',
        poster_path: "/yHoH1QsXuAPOBEbs6FWAqkHSYBL.jpg",
        media_type: "tv",
        genre_ids: [18, 35, 10751],
        popularity: 29.522,
        first_air_date: "2021-07-10",
        vote_average: 7.8,
        vote_count: 29,
        origin_country: ["CN"],
      },
      {
        adult: false,
        backdrop_path: "/wRZZCP33wVM4JhnxClnUH35jueE.jpg",
        id: 110966,
        name: "Perfect and Casual",
        original_language: "zh",
        original_name: "完美先生和差不多小姐",
        overview:
          'This story revolves around the cold and icy "male god" professor Zhang Sinian and the calm and sunny Yun Shu. After a fractious first meeting, where Yun Shu dressed down the especially finicky Sinian, she was shocked to find out that he was her university lecturer. Through a series of coincidental encounters, the two agreed to engage in a contractual marriage. As the feelings between them grow, how will they keep their relationship from those around them?',
        poster_path: "/vFsSSAIGcsBKExxlJas5MlJmRtG.jpg",
        media_type: "tv",
        genre_ids: [35, 18],
        popularity: 12.745,
        first_air_date: "2020-09-28",
        vote_average: 8.3,
        vote_count: 13,
        origin_country: ["CN"],
      },
      {
        adult: false,
        backdrop_path: "/A5sCms0ZO0uJcgfqpCE8SNujs8W.jpg",
        id: 98830,
        name: "Find Yourself",
        original_language: "zh",
        original_name: "下一站是幸福",
        overview:
          "A determined entrepreneur navigates a love triangle between a young charmer and an older executive, leading her down an unconventional path to love.",
        poster_path: "/mMfgXLuWsnDRfQPeg6Fihdh7TZn.jpg",
        media_type: "tv",
        genre_ids: [18],
        popularity: 31.947,
        first_air_date: "2020-01-26",
        vote_average: 7.578,
        vote_count: 109,
        origin_country: ["CN"],
      },
    ],
  },
  {
    adult: false,
    gender: 2,
    id: 192,
    known_for_department: "Acting",
    name: "Morgan Freeman",
    original_name: "Morgan Freeman",
    popularity: 92.179,
    profile_path: "/jPsLqiYGSofU4s6BjrxnefMfabb.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/dYjZ27hDw2QFaEIfzbNGwW0IkV9.jpg",
        id: 807,
        title: "Se7en",
        original_language: "en",
        original_title: "Se7en",
        overview:
          'Two homicide detectives are on a desperate hunt for a serial killer whose crimes are based on the "seven deadly sins" in this dark and haunting film that takes viewers from the tortured remains of one victim to the next. The seasoned Det. Sommerset researches each sin in an effort to get inside the killer\'s mind, while his novice partner, Mills, scoffs at his efforts to unravel the case.',
        poster_path: "/6yoghtyTpznpBik8EngEmJskVUO.jpg",
        media_type: "movie",
        genre_ids: [80, 9648, 53],
        popularity: 69.021,
        release_date: "1995-09-22",
        video: false,
        vote_average: 8.371,
        vote_count: 19701,
      },
      {
        adult: false,
        backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
        id: 278,
        title: "The Shawshank Redemption",
        original_language: "en",
        original_title: "The Shawshank Redemption",
        overview:
          "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        media_type: "movie",
        genre_ids: [18, 80],
        popularity: 137.888,
        release_date: "1994-09-23",
        video: false,
        vote_average: 8.706,
        vote_count: 25070,
      },
      {
        adult: false,
        backdrop_path: "/ozVwXlfxqNsariipatGwa5px3Pm.jpg",
        id: 240832,
        title: "Lucy",
        original_language: "en",
        original_title: "Lucy",
        overview:
          "A woman, accidentally caught in a dark deal, turns the tables on her captors and transforms into a merciless warrior evolved beyond human logic.",
        poster_path: "/dhjyfcwEoW6jJ4Q7DpZTp6E58GA.jpg",
        media_type: "movie",
        genre_ids: [28, 878],
        popularity: 51.159,
        release_date: "2014-07-25",
        video: false,
        vote_average: 6.443,
        vote_count: 15308,
      },
    ],
  },
  {
    adult: false,
    gender: 1,
    id: 1954014,
    known_for_department: "Acting",
    name: "Leya Kırşan",
    original_name: "Leya Kırşan",
    popularity: 91.969,
    profile_path: "/6BnGIrF2s4z96rFlknjv7Qe2jyL.jpg",
    known_for: [
      {
        adult: false,
        backdrop_path: "/ndLd4IIc90ajv5VpCaLfqmmEYOb.jpg",
        id: 95603,
        name: "Kuruluş Osman",
        original_language: "tr",
        original_name: "Kuruluş Osman",
        overview:
          "The life of Osman Bey, the son of Ertugrul Gazi and the founder of the Ottoman Empire.",
        poster_path: "/tt3Myy0jYTiLETjNXu78HORUXLq.jpg",
        media_type: "tv",
        genre_ids: [10768, 10759, 18],
        popularity: 262.677,
        first_air_date: "2019-11-20",
        vote_average: 8,
        vote_count: 262,
        origin_country: ["TR"],
      },
      {
        adult: false,
        backdrop_path: "/8LJ2cfKGchqF8lYLN3I7qeWZr0j.jpg",
        id: 72066,
        name: "The Name is Legend",
        original_language: "tr",
        original_name: "Adı Efsane",
        overview: "",
        poster_path: "/9iddnF4PiyzodSFnJ0dNeMl4NJm.jpg",
        media_type: "tv",
        genre_ids: [18],
        popularity: 6.707,
        first_air_date: "2017-01-28",
        vote_average: 5.8,
        vote_count: 5,
        origin_country: ["TR"],
      },
      {
        adult: false,
        backdrop_path: "/nXSgPvCYMtFYmZfVEoavJMmm2tC.jpg",
        id: 120131,
        name: "Tozkoparan: İskender",
        original_language: "tr",
        original_name: "Tozkoparan: İskender",
        overview:
          "If Iskender, a 12-year-old archer with extraordinary abilities, does not return from 2020 to the time he lived, the course of history will change.",
        poster_path: "/z1QxafIMhZHQrUC9HDUyOPKIF43.jpg",
        media_type: "tv",
        genre_ids: [10751, 10759],
        popularity: 19.425,
        first_air_date: "2021-01-03",
        vote_average: 7.667,
        vote_count: 3,
        origin_country: ["TR"],
      },
    ],
  },
];

export default actors;
